### ISSUE TITLE
Navigation back event does not close side navigation menu

### ISSUE THREAD

**Issue by RascalTwo** [TMJSMC53/holistic-health-app#2]
# Expected Behavior

Clicking the back button closes the side navigation menu.

# Actual Behavior

Clicking the back button causes navigation to the previous page, with the side navigation menu still on top if the previous page is still on holistic health.

https://github.com/TMJSMC53/holistic-health-app/assets/9403665/8e313d52-f2e7-4fc4-8970-9c04f557b890

# Steps to Reproduce the Problem

- Navigate to the homepage
- Open the side navigation menu
- Click on the About page link
- Open the side navigation menu
- Click the Back button

This behavior is the same in Firefox, Chrome, Desktop & Mobile.

**Comment by TMJSMC53** [comment]
@RascalTwo thank you and it is being worked on

**Comment by TMJSMC53** [comment]
Resolved: This issue has been resolved. The bug was fixed in commit 11c729f
